#
#
#
include ../Makefile.defs

LIBNAME=oa
SRCS=  \
        oaWriter.cpp \
        oaReader.cpp

#CXXFLAGS += -I/u/twg/oa_2_2_p018/include


##############################################
# Add custom targets below the following line.
include ../Makefile.rules
