#ifndef ADS_DB_TECH_VIA_H
#define ADS_DB_TECH_VIA_H

#ifndef ADS_H
#include "ads.h"
#endif

#ifndef ADS_DB_TYPES_H
#include "dbTypes.h"
#endif

#ifndef ADS_DB_ID_H
#include "dbId.h"
#endif

#ifndef ADS_DB_OBJECT_H
#include "dbObject.h"
#endif

#ifndef ADS_DB_VIA_PARAMS_H
#include "dbViaParams.h"
#endif

BEGIN_NAMESPACE_ADS

class _dbBox;
class _dbTechLayer;
class _dbTechViaGenerateRule;
class _dbTechNonDefaultRule;
class _dbDatabase;
class dbIStream;
class dbOStream;
class dbDiff;

struct _dbTechViaFlags
{
    uint               _default_via  : 1; 
    uint               _top_of_stack : 1; 
    uint               _has_params   : 1; 
    uint               _spare_bits   : 29; 
};

class _dbTechVia : public dbObject
{
  public:
    // PERSISTANT-MEMBERS
    _dbTechViaFlags              _flags;
    double                       _resistance;
    char *                       _name;
    char *                       _pattern;
    dbId<_dbBox>                 _bbox;   // Caching the bbox speeds up defin imports.
    dbId<_dbBox>                 _boxes;
    dbId<_dbTechLayer>           _top;    // Caching the layer speeds up defin imports.
    dbId<_dbTechLayer>           _bottom; // Caching the layer speeds up defin imports.
    dbId<_dbTechNonDefaultRule>  _non_default_rule;   // non-default-rule
    dbId<_dbTechViaGenerateRule> _generate_rule;   // via generated by tech-via-rule, 5.6 DEF
    _dbViaParams                 _via_params;      // params used to generate this via, 5.6 DEF

    _dbTechVia( _dbDatabase *, const _dbTechVia & v );
    _dbTechVia( _dbDatabase * );
    ~_dbTechVia();

    int operator==( const _dbTechVia  & rhs ) const;
    int operator!=( const _dbTechVia  & rhs ) const { return ! operator==(rhs); }
    void differences( dbDiff & diff, const char * field, const _dbTechVia  & rhs ) const;
    void out( dbDiff & diff, char side, const char * field ) const;
};

dbOStream & operator<<( dbOStream & stream, const _dbTechVia & via );
dbIStream & operator>>( dbIStream & stream, _dbTechVia & via );

END_NAMESPACE_ADS

#endif
