#
#
#
include ../Makefile.defs

LIBNAME=sdcrypt
SRCS=   sdcrypt.cpp Blowfish.cpp

##############################################
# Add custom targets below the following line.
include ../Makefile.rules
